#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.

if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export LANG=en_US.UTF-8
export PATH=$HOME/.local/bin:$PATH:$HOME/.cargo/bin/
export VISUAL=nvim
export EDITOR='vi'
export TERM="xterm-256color"
export PAGER='less'

export GTAGSCONF=/usr/share/gtags/gtags.conf
export GTAGSLABEL=pygments
